version: '3.4'
services:
  app:
    image: nicolkill/dbb:latest
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - 4000:4000
    environment:
      ALLOWED_SITES: "*"
      CONFIG_SCHEMA: config.json

      # db config
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_HOSTNAME: postgres

  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
