FROM hexpm/elixir:1.19.5-erlang-28.0.1-alpine-3.23.3

RUN apk update \
    && apk add --no-cache \
    git \
    curl \
    inotify-tools \
    build-base \
    make \
    linux-headers

RUN echo "#include <unistd.h>" > /usr/include/sys/unistd.h

# Install hex and rebar
RUN mix local.rebar --force && \
    mix local.hex --force

ENV APP_HOME /app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
COPY . .

ADD docker-entrypoint.sh .
ENTRYPOINT ["./docker-entrypoint.sh"]

CMD ["start"]
